package com.example.late_plate.model

data class Classification(
    val name:String,
    val score:Float
)
data class ClassNames(
    val classNames: List<String> = listOf(
        "onion",
        "corn",
        "lettuce",
        "potato",
        "clove",
        "avocado",
        "fennel",
        "coriander leaves",
        "tarragon",
        "garlic",
        "cabbage",
        "dragon fruit",
        "cherry",
        "lemongrass",
        "cauliflower",
        "beetroot",
        "orange",
        "chili flakes",
        "strawberry",
        "pumpkin",
        "lime leaves",
        "chili pepper",
        "rosemary",
        "candlenut",
        "cardamom",
        "star anise",
        "vanilla",
        "Artichoke",
        "thyme",
        "blackberry",
        "raddish",
        "sweetpotato",
        "broccoli",
        "pepper",
        "cumin",
        "mango",
        "carrot",
        "lemon",
        "jalepeno",
        "tomato",
        "watermelon",
        "zucchini",
        "ginger",
        "bell pepper",
        "spinach",
        "banana",
        "turnip",
        "kiwi",
        "soy beans",
        "grapes",
        "bay leaf",
        "Asparagus",
        "apple",
        "lychee",
        "coconut",
        "nutmeg",
        "saffron",
        "pomegranate",
        "parsley",
        "basil leave",
        "tamarind",
        "turmeric",
        "eggplant",
        "pear",
        "cinnamon",
        "cucumber",
        "pineapple"
    )
)
